#!/usr/bin/env python3
"""Write `docs/reports/open-findings.md`: every finding this project currently reports.

Maintaining this? Start at `docs/coherence.md`.

Two files, because they answer different questions and have different audiences.
`docs/reports/open-findings.md` is the report: what anoieu believes and nobody has ruled
on, and the thing another project is pointed at. `docs/reports/closed-findings.md` is
the ledger of verdicts: internal bookkeeping, written by review and read by this
generator, which skips any id listed in either.

Two sources, one table. The **checks** are re-derived on every run, over the
corpora in `deps/`. The **fuzzer** cannot be -- re-deriving one of its findings
means running somebody else's binary, which this job does not have -- so its
findings come from `tests/fuzz/`, the reproducers a person promoted, and are
told apart by their `FUZ` code.

**Additive only.** This generator adds rows and never removes one. A finding
that has stopped being reported stays in the file until something *else* takes
it out — see "How this file is maintained" in the generated header. The
asymmetry is deliberate: a generator that could delete could also quietly delete
a regression, and the whole value of the file is that a row cannot vanish
without someone saying why.

    python3 tools/gen_open_findings.py             # add anything new
    python3 tools/gen_open_findings.py --check     # exit 1 if something is unlisted
    python3 tools/gen_open_findings.py --roots elsewhere

`--check` fails only when a finding is *missing* from the file. Extra rows —
findings no longer reported — are never an error here, because deciding they are
closed is a judgement, not a diff.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from anoieu.checks import Context, load_checks, run_all  # noqa: E402
from anoieu.cli import _embedding_vocabulary  # noqa: E402
from anoieu.fingerprint import fingerprint  # noqa: E402
from anoieu.loader import load  # noqa: E402
from anoieu.semantics import load_set  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_corpus_table import DEFAULT_ROOTS, TARGETS, not_audited, signatures  # noqa: E402

from anoieu_fuzz.report import rows as fuzz_rows  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "reports", "open-findings.md")
LEDGER = os.path.join(ROOT, "docs", "reports", "closed-findings.md")

HEADER = """# Open findings

Every finding anoieu currently reports on the corpora it watches, one row each.
Generated by `tools/gen_open_findings.py`.

**If a row was sent to you, this is the page to start on.**

## What a row is

A row is a *claim*, not a diagnosis. It says what anoieu believes, where, and
under which code — it does not say what kind of problem to expect, and some of
it will be wrong. Nobody who owns the file has necessarily seen it. The `id` is
what everything else refers to; it survives edits elsewhere in the file, and it
is what to quote. Rows move, so work from ids rather than from positions.

## How to confirm one, by code

Two kinds of row, confirmed two different ways. The code says which.

| code | what it is | how you confirm it |
| --- | --- | --- |
| `EO`, `DOC`, `TRI` | a **check** read something out of a signature. One page per code in [`checks.md`](checks.md) — link straight to yours, `checks.md#eo0054` and so on | the row names a file and a line **in your project**: read that file |
| `FUZ` | the **[fuzzer](fuzzing.md)** provoked it out of a running checker. Codes are [one page each](fuzzing.md#the-codes) | the row names a committed reproducer under [`tests/fuzz/`](../tests/fuzz), fetchable raw: **run your own build on it** |

A `FUZ` row is about a program's *behaviour*, not about a file anyone maintains,
and it was produced against somebody else's build — so it may not reproduce for
you at all, which is itself a result worth reporting. It says which *direction* a
disagreement runs in, never which checker is wrong: the serious direction can
still end with the reference being stricter than the language requires.

## What to do with one

Decide whether it is real, by reading the file or running the reproducer, rather
than by trusting the row. Then fix it, decline it with a reason, or say you
cannot tell — all three are results. The reply goes back in the shape set out in
[`reporting-workflow.md`](reporting-workflow.md#the-shape-of-a-reply), which also
says why an assistant's triage and a person's decision are kept in separate
fields, and asks for feedback on this process in the other direction.

**What settling one takes from you is small, and it is not a merge.** Put the
fix on a branch, push the branch, and tell us where it is; a change nobody has
committed is one we have no way to read, and it is the only thing that has ever
held a row open here after its maintainer had accepted it. We do **not** wait
for the branch to reach your default branch before closing the finding — your
word that it will is enough, and whether it did is a question we ask separately,
of the commit, and never of you. Declining takes less: say so in as many words.
Silence is the one answer we cannot record, because we cannot tell it from
nobody having looked.

**A quiet corpus is not a clean one**, and a check that reports nothing is not
evidence that anything is right: see *What we do not publish* in the top-level
README. What has happened to findings already reported — including the ones we
got wrong — is in [`reports.md`](reports.md#the-log-what-was-reported-and-what-came-back).

## Two tables, and what is not here

Rows that have been **ruled on are not in this file**. They are in
[`closed-findings.md`](closed-findings.md) with the verdict against each: that
one is internal bookkeeping, but it is where a finding's *answer* lives, so a row
here may already have a settled twin under another id. Where we know of one, the
`notes` column says so.

Generation is additive — it adds rows and never removes one, so a finding cannot
vanish without somebody saying why, and nothing in the `notes` column is ever
overwritten. Closing is a separate, deliberate step that moves a row to the other
file. The rules for both are in
[`reporting-workflow.md`](reporting-workflow.md#the-conventions).
"""

COLUMNS = "| id | owner | code | where | what | notes |"
DIVIDER = "| --- | --- | --- | --- | --- | --- |"
LEDGER_HEADER = """# Closed findings

**Internal.** Every finding that has been ruled on, with the verdict against it.
This is the half of the ledger nobody is asked to read: the report is
[`open-findings.md`](open-findings.md), and the reasoning behind each verdict is
in [`reports.md`](reports.md#the-log-what-was-reported-and-what-came-back).

Kept as a file, and kept in git, for three reasons.

1. **It is what makes a verdict stick.** `tools/gen_open_findings.py` skips any
   id listed here. A row simply deleted from the report would be found again on
   the next run, because the finding is still there to be found.
2. **A row is moved here, never deleted.** Closing is a judgement somebody
   signs, and the diff that moves a row is the record of it.
3. **A verdict is a claim about the world, and can go stale.** *fixed upstream*
   was recorded three times for a fix that never landed, and it went unnoticed
   for as long as it did because a closed id is one nothing re-derives. Where a
   verdict depends on somebody else's tree, it should say which commit it was
   checked at.

**Most rows here are closed before their change has landed, on purpose.** A row
closes when a maintainer accepted it and the change is a commit on a named
branch; waiting for a merge would hold findings open for as long as somebody
else's review queue, which says nothing about the finding. The full rule is
[what closes a row](reporting-workflow.md#what-closes-a-row-and-what-does-not).

That is exactly the shape of the mistake in reason 3, taken on deliberately, so
it is booked rather than assumed away. Such a row ends its verdict with

    awaiting landing: <project> <branch> <commit>

and `python3 tools/landing.py --check` reads every one of them back and asks the
project's checkout whether that commit has reached the default branch. It is a
separate pass with its own question -- *did what we closed actually land* -- and
`tests/run.py` fails if a marker is reworded into something it cannot parse,
because that would drop a row from the audit while leaving the debt owed. When a
change lands, a person replaces the marker with what landed it.

Written by hand, by the review step in
[`reporting-workflow.md`](reporting-workflow.md#the-workflow). The generator reads
it and rewrites it, and rewriting preserves every row.

| id | owner | code | where | what | verdict |
| --- | --- | --- | --- | --- | --- |"""
_ROW = re.compile(r"^\| `([0-9a-f]{6,})` \|")


def owner_of(path: str, roots: dict) -> str:
    for name, root in roots.items():
        if os.path.abspath(path).startswith(os.path.abspath(root) + os.sep):
            return name
    return "—"


def collect(roots: dict) -> dict[str, dict]:
    """Every finding, keyed by the fingerprint a closing step refers to."""
    load_checks()
    out: dict[str, dict] = {}
    for _label, repo, rels, triple in TARGETS:
        paths = [os.path.join(roots[repo], r) for r in rels]
        needed = list(paths) + (
            [os.path.join(roots[r], rel) for r, rel in triple.values()] if triple else []
        )
        if not all(os.path.exists(p) for p in needed):
            continue
        sem = smt = None
        embed: set[str] = set()
        if triple:
            r, rel = triple["semantics"]
            sem = load_set(os.path.join(roots[r], rel))
            r, rel = triple["smt"]
            smt = load_set(os.path.join(roots[r], rel))
            r, rel = triple["embedding"]
            embed = _embedding_vocabulary(os.path.join(roots[r], rel))
        skip = not_audited(repo, roots[repo])
        for group in signatures(paths, skip):
            result = load(group)
            ctx = Context(
                signature=result.signature,
                files=result.files,
                sources=result.sources,
                root=roots[repo],
                include_edges=result.include_edges,
                semantics=sem,
                smt_semantics=smt,
                embedding_names=embed,
            )
            for d in list(result.diagnostics) + run_all(ctx):
                if d.code.startswith("ANO"):
                    continue
                if os.path.abspath(d.span.path) in skip:
                    continue  # see NOT_AUDITED in tools/gen_corpus_table.py
                owner = owner_of(d.span.path, roots)
                key = fingerprint(d, result.sources, roots.get(owner, roots[repo]))
                if key in out:
                    continue
                where = os.path.relpath(d.span.path, roots.get(owner, roots[repo]))
                out[key] = {
                    "owner": owner,
                    "code": d.code,
                    "where": f"{where}:{d.span.line}",
                    "what": d.message.replace("|", "\\|"),
                }
    # and the findings that came from the other half. They are keyed by the
    # same fingerprint and shaped the same way, so from here down nothing
    # distinguishes them but their code -- which is the point.
    for key, row in fuzz_rows().items():
        out.setdefault(key, row)
    return out


def _rows(path: str) -> list[str]:
    """Every table row of a file, in order, or nothing if it is not there."""
    if not os.path.isfile(path):
        return []
    return [l for l in open(path).read().splitlines() if _ROW.match(l)]


def existing(report: str, ledger: str) -> tuple[list[str], list[str], set[str]]:
    """The open rows, the closed rows, and every id already accounted for.

    Two files since the ledger moved out of the report. A row that has not yet
    been split out -- an `open-findings.md` from before the move, still carrying
    its own `## Closed` section -- is read from where it stands, so that running
    the generator performs the move rather than losing the verdicts.
    """
    open_rows = closed_rows = []
    if os.path.isfile(report):
        head, sep, tail = open(report).read().partition("## Closed")
        open_rows = [l for l in head.splitlines() if _ROW.match(l)]
        closed_rows = [l for l in tail.splitlines() if _ROW.match(l)] if sep else []
    closed_rows = closed_rows + [
        l for l in _rows(ledger) if l not in closed_rows
    ]
    ids = {m.group(1) for l in open_rows + closed_rows if (m := _ROW.match(l))}
    return open_rows, closed_rows, ids


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roots", help="a directory of clones; defaults to deps/")
    ap.add_argument("--check", action="store_true", help="exit 1 if a finding is unlisted")
    args = ap.parse_args()

    roots = dict(DEFAULT_ROOTS)
    if args.roots:
        roots = {name: os.path.join(args.roots, name) for name in DEFAULT_ROOTS}

    found = collect(roots)
    kept, closed, listed = existing(OUT, LEDGER)
    missing = {k: v for k, v in found.items() if k not in listed}

    if args.check:
        if not missing:
            print(
                f"-- docs/reports/open-findings.md lists every finding "
                f"({len(kept)} open, {len(closed)} closed)"
            )
            return 0
        print(
            f"-- {len(missing)} finding(s) are not listed in docs/reports/open-findings.md; "
            "run tools/gen_open_findings.py and commit",
            file=sys.stderr,
        )
        for k, v in sorted(missing.items(), key=lambda kv: kv[1]["where"]):
            print(f"   {k}  {v['owner']}  {v['code']}  {v['where']}", file=sys.stderr)
        return 1

    added = [
        f"| `{k}` | {v['owner']} | {v['code']} | `{v['where']}` | {v['what']} |  |"
        for k, v in sorted(missing.items(), key=lambda kv: (kv[1]["owner"], kv[1]["where"]))
    ]
    body = [HEADER.rstrip(), "", "## Open", "", COLUMNS, DIVIDER] + kept + added
    with open(OUT, "w") as f:
        f.write("\n".join(body).rstrip() + "\n")
    with open(LEDGER, "w") as f:
        f.write("\n".join([LEDGER_HEADER] + closed).rstrip() + "\n")
    print(
        f"-- wrote docs/reports/open-findings.md: {len(added)} added, {len(kept)} open"
    )
    print(f"-- wrote docs/reports/closed-findings.md: {len(closed)} ruled on")
    return 0


if __name__ == "__main__":
    sys.exit(main())
