#!/usr/bin/env python3
"""Write `docs/open-findings.md`: every finding this project currently reports.

Two sources, one table. The **checks** are re-derived on every run, over the
corpora in `deps/`. The **fuzzer** cannot be -- re-deriving one of its findings
means running somebody else's binary, which this job does not have -- so its
findings come from `tests/fuzz/`, the reproducers a person promoted, and are
told apart by their `FUZ` code.

**Additive only.** This generator adds rows and never removes one. A finding
that has stopped being reported stays in the file until something *else* takes
it out — see "How this file is maintained" in the generated header. The
asymmetry is deliberate: a generator that could delete could also quietly delete
a regression, and the whole value of the file is that a row cannot vanish
without someone saying why.

    python3 tools/gen_open_findings.py             # add anything new
    python3 tools/gen_open_findings.py --check     # exit 1 if something is unlisted
    python3 tools/gen_open_findings.py --roots elsewhere

`--check` fails only when a finding is *missing* from the file. Extra rows —
findings no longer reported — are never an error here, because deciding they are
closed is a judgement, not a diff.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from anoieu.checks import Context, load_checks, run_all  # noqa: E402
from anoieu.cli import _embedding_vocabulary  # noqa: E402
from anoieu.fingerprint import fingerprint  # noqa: E402
from anoieu.loader import load  # noqa: E402
from anoieu.semantics import load_set  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_corpus_table import DEFAULT_ROOTS, TARGETS, signatures  # noqa: E402

from anoieu_fuzz.report import rows as fuzz_rows  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "open-findings.md")

HEADER = """# Open findings

Every finding the checks report on the corpora this project watches, one row
each, with the id a closing step refers to. Generated by
`tools/gen_open_findings.py`.

Rows come from two places, and the code says which. `EO`, `DOC` and `TRI` are
what the **checks** read out of a signature, re-derived on every run. `FUZ` is
what the **anoieu fuzzer** provoked out of a checker — see
[`fuzzing.md`](fuzzing.md) — and its evidence is a committed reproducer under
`tests/fuzz/` plus the verdicts recorded beside it, because re-deriving one
means running a binary this job does not have.

**Not a verdict.** A row here is something anoieu believes; nobody who owns the
file has necessarily seen it, and some of it will be wrong — see
[`reports.md`](reports.md#the-log-what-was-reported-and-what-came-back) for what has happened to the findings that were
reported, including the one we got wrong. And a quiet corpus is not a clean
one: see *What we do not publish* in the top-level README.

## How this file is maintained

This is the intended arrangement for the medium term, and the asymmetry in it is
the point:

1. **Generation is additive.** `tools/gen_open_findings.py` adds a row for any
   finding whose id appears nowhere in this file, and *never removes one*. CI
   runs it with `--check`, which fails when something is unlisted and never when
   something is extra.
2. **Closing is a separate, deliberate step.** A finding leaves the open table
   when it is fixed upstream, declined, or shown to be our error — and that
   judgement is made by review, not by the finding's absence on a later run. For
   now that review is an AI process working over this table under human
   supervision: it takes a row, checks the state of the file it is about, and
   either leaves it or **moves it to *Closed* below** with a verdict, writing
   what happened into [`reports.md`](reports.md#the-log-what-was-reported-and-what-came-back).
3. **Closing means moving, not deleting.** A row that were simply deleted would
   come back on the next generation, because the finding is still there to be
   found. The *Closed* table is what makes a verdict stick: the generator skips
   any id listed in this file, in either table.
4. **Nothing disappears silently.** A finding that stops being reported is not
   evidence that it was addressed — it may have moved, or a check may have been
   narrowed — which is why the generator cannot delete and why every closure
   leaves both a row and a line in the log.

The hand-written register in [`reports.md`](reports.md#the-register-what-anoieu-is-asking-and-of-whom) is the first pass at this,
kept as the worked example of what a curated report looks like; this file is
where the mechanical half now lives.

"""

COLUMNS = "| id | owner | code | where | what | notes |"
DIVIDER = "| --- | --- | --- | --- | --- | --- |"
CLOSED = """## Closed

Findings that have been ruled on. A row is moved here by the review step, never
by the generator, and its id is what stops the finding being listed again. The
reasoning belongs in [`reports.md`](reports.md#the-log-what-was-reported-and-what-came-back); this table is the ledger.

| id | owner | code | where | what | verdict |
| --- | --- | --- | --- | --- | --- |"""
_ROW = re.compile(r"^\| `([0-9a-f]{6,})` \|")


def owner_of(path: str, roots: dict) -> str:
    for name, root in roots.items():
        if os.path.abspath(path).startswith(os.path.abspath(root) + os.sep):
            return name
    return "—"


def collect(roots: dict) -> dict[str, dict]:
    """Every finding, keyed by the fingerprint a closing step refers to."""
    load_checks()
    out: dict[str, dict] = {}
    for _label, repo, rels, triple in TARGETS:
        paths = [os.path.join(roots[repo], r) for r in rels]
        needed = list(paths) + (
            [os.path.join(roots[r], rel) for r, rel in triple.values()] if triple else []
        )
        if not all(os.path.exists(p) for p in needed):
            continue
        sem = smt = None
        embed: set[str] = set()
        if triple:
            r, rel = triple["semantics"]
            sem = load_set(os.path.join(roots[r], rel))
            r, rel = triple["smt"]
            smt = load_set(os.path.join(roots[r], rel))
            r, rel = triple["embedding"]
            embed = _embedding_vocabulary(os.path.join(roots[r], rel))
        for group in signatures(paths):
            result = load(group)
            ctx = Context(
                signature=result.signature,
                files=result.files,
                sources=result.sources,
                root=roots[repo],
                include_edges=result.include_edges,
                semantics=sem,
                smt_semantics=smt,
                embedding_names=embed,
            )
            for d in list(result.diagnostics) + run_all(ctx):
                if d.code.startswith("ANO"):
                    continue
                owner = owner_of(d.span.path, roots)
                key = fingerprint(d, result.sources, roots.get(owner, roots[repo]))
                if key in out:
                    continue
                where = os.path.relpath(d.span.path, roots.get(owner, roots[repo]))
                out[key] = {
                    "owner": owner,
                    "code": d.code,
                    "where": f"{where}:{d.span.line}",
                    "what": d.message.replace("|", "\\|"),
                }
    # and the findings that came from the other half. They are keyed by the
    # same fingerprint and shaped the same way, so from here down nothing
    # distinguishes them but their code -- which is the point.
    for key, row in fuzz_rows().items():
        out.setdefault(key, row)
    return out


def existing(path: str) -> tuple[list[str], list[str], set[str]]:
    """The open rows, the closed rows, and every id the file already knows."""
    if not os.path.isfile(path):
        return [], [], set()
    text = open(path).read()
    head, _, tail = text.partition("## Closed")
    open_rows = [l for l in head.splitlines() if _ROW.match(l)]
    closed_rows = [l for l in tail.splitlines() if _ROW.match(l)]
    ids = {
        m.group(1) for l in open_rows + closed_rows if (m := _ROW.match(l))
    }
    return open_rows, closed_rows, ids


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roots", help="a directory of clones; defaults to deps/")
    ap.add_argument("--check", action="store_true", help="exit 1 if a finding is unlisted")
    args = ap.parse_args()

    roots = dict(DEFAULT_ROOTS)
    if args.roots:
        roots = {name: os.path.join(args.roots, name) for name in DEFAULT_ROOTS}

    found = collect(roots)
    kept, closed, listed = existing(OUT)
    missing = {k: v for k, v in found.items() if k not in listed}

    if args.check:
        if not missing:
            print(
                f"-- docs/open-findings.md lists every finding "
                f"({len(kept)} open, {len(closed)} closed)"
            )
            return 0
        print(
            f"-- {len(missing)} finding(s) are not listed in docs/open-findings.md; "
            "run tools/gen_open_findings.py and commit",
            file=sys.stderr,
        )
        for k, v in sorted(missing.items(), key=lambda kv: kv[1]["where"]):
            print(f"   {k}  {v['owner']}  {v['code']}  {v['where']}", file=sys.stderr)
        return 1

    added = [
        f"| `{k}` | {v['owner']} | {v['code']} | `{v['where']}` | {v['what']} |  |"
        for k, v in sorted(missing.items(), key=lambda kv: (kv[1]["owner"], kv[1]["where"]))
    ]
    body = (
        [HEADER.rstrip(), "", "## Open", "", COLUMNS, DIVIDER]
        + kept
        + added
        + ["", CLOSED]
        + closed
    )
    with open(OUT, "w") as f:
        f.write("\n".join(body).rstrip() + "\n")
    print(
        f"-- wrote docs/open-findings.md: {len(added)} added, {len(kept)} open, "
        f"{len(closed)} closed"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
