#!/usr/bin/env python3
"""Write `docs/corpus.md`: what the checks report on the signatures we can find.

Generated rather than written, for the reason every counted thing should be:
a number typed by hand is a number that was true once. `--check` says whether
the file is current and is what CI runs.

A failure means one of two things, and both are worth a look: upstream moved, or
a check of ours changed what it reports. Neither is an error in itself, and the
diff says which.

    python3 tools/gen_corpus_table.py            # rewrite docs/corpus.md
    python3 tools/gen_corpus_table.py --check    # exit 1 if it is stale
    python3 tools/gen_corpus_table.py --roots elsewhere   # another set of clones

The table counts findings. It is not a score and not a comparison between
repositories: a corpus with fewer findings has not been shown to be better, only
to have tripped fewer of the checks that exist. See *What we do not publish* in
the top-level README.
"""

from __future__ import annotations

import argparse
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from anoieu.checks import Context, load_checks, run_all  # noqa: E402
from anoieu.cli import _embedding_vocabulary  # noqa: E402
from anoieu.diagnostics import Severity  # noqa: E402
from anoieu.loader import load  # noqa: E402
from anoieu.semantics import load_set  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "corpus.md")

# Each target: a label, the signatures of one profile, and optionally the other
# legs of a triple. Paths are relative to a repository root named below.
TARGETS = [
    ("CPC", "cvc5", ["proofs/eo/cpc/Cpc.eo"], None),
    (
        "CPC with the expert signature",
        "cvc5",
        ["proofs/eo/cpc/Cpc.eo", "proofs/eo/cpc/expert/CpcExpert.eo"],
        None,
    ),
    ("ethos test signatures", "ethos", ["tests"], None),
    ("logos installed definitions", "logos", ["install/defs"], None),
    # `examples/hello` only: `examples/cpc` is a vendored copy of cvc5's
    # signature, so checking it reports cvc5's findings under eudaimonia's name.
    ("eudaimonia examples", "eudaimonia", ["examples/hello"], None),
    (
        "the CPC triple",
        "cvc5",
        ["proofs/eo/cpc/Cpc.eo"],
        {
            "semantics": ("logos", "install/defs/Cpc.eos"),
            "smt": ("ethos", "tools/eoc/semantics/smt.eos"),
            "embedding": ("ethos", "plugins/model_smt/model_smt.eo"),
        },
    ),
]

# Where the sources live: clones this project manages, never a checkout somebody
# else owns. See tools/deps.py.
from deps import roots as _dep_roots  # noqa: E402

DEFAULT_ROOTS = _dep_roots()


def signatures(paths: list[str]) -> list[list[str]]:
    """A directory is one profile per file; files together are one profile."""
    out: list[list[str]] = []
    files: list[str] = []
    for p in paths:
        if os.path.isdir(p):
            for root, _dirs, names in os.walk(p):
                out += [[os.path.join(root, n)] for n in sorted(names) if n.endswith(".eo")]
        else:
            files.append(p)
    return ([files] if files else []) + out


def measure(paths: list[str], triple: dict | None, roots: dict) -> tuple[collections.Counter, int]:
    load_checks()
    sem = smt = None
    embed: set[str] = set()
    if triple:
        r, rel = triple["semantics"]
        sem = load_set(os.path.join(roots[r], rel))
        r, rel = triple["smt"]
        smt = load_set(os.path.join(roots[r], rel))
        r, rel = triple["embedding"]
        embed = _embedding_vocabulary(os.path.join(roots[r], rel))

    codes: collections.Counter = collections.Counter()
    files: set[str] = set()
    # the same dedupe the command line does: a finding in a file two profiles
    # both read is one finding, not two
    seen: set[tuple] = set()
    for group in signatures(paths):
        result = load(group)
        ctx = Context(
            signature=result.signature,
            files=result.files,
            sources=result.sources,
            root=os.path.dirname(group[0]),
            include_edges=result.include_edges,
            semantics=sem,
            smt_semantics=smt,
            embedding_names=embed,
        )
        files |= set(result.files)
        for d in list(result.diagnostics) + run_all(ctx):
            key = (d.span.path, d.span.line, d.span.col, d.code, d.message)
            if key in seen:
                continue
            seen.add(key)
            codes[(d.code, d.severity)] += 1
    return codes, len(files)


def render(rows: list[tuple[str, collections.Counter, int, bool]]) -> str:
    out = ["""# What the checks report on the corpus

Generated by `tools/gen_corpus_table.py`; `--check` says whether it is current,
and CI runs that. Every number here is a count of *findings*, at the severities
that are on by default.

**This is not a score, and not a comparison between repositories.** A corpus
with fewer findings has not been shown to be better — only to have tripped fewer
of the checks that happen to exist, each of which is partial and has been
narrowed until it stopped over-reporting. See *What we do not publish* in the
top-level README.

"""]
    out.append("| corpus | files | errors | warnings | hints |")
    out.append("| --- | ---: | ---: | ---: | ---: |")
    for label, codes, nfiles, ok in rows:
        if not ok:
            out.append(f"| {label} | — | — | — | — |")
            continue
        sev = collections.Counter()
        for (_code, s), n in codes.items():
            sev[s] += n
        out.append(
            f"| {label} | {nfiles} | {sev[Severity.ERROR]} | "
            f"{sev[Severity.WARNING]} | {sev[Severity.HINT]} |"
        )
    out.append("")
    out.append("## By check")
    out.append("")
    for label, codes, _nfiles, ok in rows:
        if not ok:
            out.append(f"**{label}** — not measured: the repository was not found.\n")
            continue
        out.append(f"**{label}**")
        out.append("")
        if not codes:
            out.append("Nothing reported by the checks that are on by default.\n")
            continue
        out.append("| code | severity | count |")
        out.append("| --- | --- | ---: |")
        for (code, sev), n in sorted(codes.items(), key=lambda kv: (-kv[1], kv[0][0])):
            out.append(f"| {code} | {sev.value} | {n} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roots", help="a directory of clones; defaults to deps/")
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/corpus.md is stale")
    args = ap.parse_args()

    roots = dict(DEFAULT_ROOTS)
    if args.roots:
        roots = {name: os.path.join(args.roots, name) for name in DEFAULT_ROOTS}

    rows = []
    for label, repo, rels, triple in TARGETS:
        paths = [os.path.join(roots[repo], r) for r in rels]
        needed = list(paths) + (
            [os.path.join(roots[r], rel) for r, rel in triple.values()] if triple else []
        )
        if not all(os.path.exists(p) for p in needed):
            rows.append((label, collections.Counter(), 0, False))
            continue
        codes, nfiles = measure(paths, triple, roots)
        rows.append((label, codes, nfiles, True))

    text = render(rows)
    if args.check:
        current = open(OUT).read() if os.path.isfile(OUT) else ""
        if current == text:
            print("-- docs/corpus.md is current")
            return 0
        print(
            "-- docs/corpus.md is stale: upstream moved, or a check changed what it "
            "reports.\n   Run tools/gen_corpus_table.py and read the diff.",
            file=sys.stderr,
        )
        return 1
    with open(OUT, "w") as f:
        f.write(text)
    measured = sum(1 for *_x, ok in rows if ok)
    print(f"-- wrote docs/corpus.md ({measured} of {len(rows)} corpora measured)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
